### ISSUE TITLE
How does exporting importing work?

### ISSUE THREAD

**Issue by Aquive** [wpalmer/magerun-cms#2]
Other then the command there is no explaination. What we tried is put the output of the command to a Json file. Like this: cms:block:dump > cms-dump.json. This works. But how do we import this agian? We tried several things without succes. Or should we export in another way?

**Comment by wpalmer** [comment]
The import format should indeed be identical to the export format. I've noticed that due to a bug, the output was not being generated correctly (was not valid json). This has now been corrected in the latest master.

Can you let me know what you've tried / what output there was, if any?

**Comment by wpalmer** [comment]
The README file has been expanded to include examples, limitations, and some intended use-cases. Let me know if this helps.

**Comment by Aquive** [comment]
I think we encountered that bug. Because it threw an error about the input data. We will try it again with the newest version and let you know if it works. Thanks for your fast reply!

**Comment by wpalmer** [comment]
As I haven't heard back, I'll consider this issue resolved for now. Please open a new issue if it remains a problem.
